services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    volumes:
      - /mnt/dietpi_userdata/uptimekuma:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped